### PR TITLE
Replace default team with world team

### PR DESCRIPTION
**Pull request by minsii**
This PR contains two changes:
- Replace default team with world team. Resolves #371 for the teams and context sections. 
- Move the introduction part into a separate file, similar to other sections.

### CODE REVIEW

**Comment by minsii** [comment]
@jdinan @agrippa @naveen-rn @wrrobin could you please review?

**Review by agrippa — APPROVED** [review]

**Comment by jdinan** [comment]
@minsii How do you want to handle updating default -> world team for the other sections?

**Comment by minsii** [comment]
@jdinan I have submitted separate PRs to the other section committee branches. Some of them have been already merged. You can see the PR list at #371

**Comment by jdinan** [comment]
Thanks, I had missed those other PRs. Did you get the instance of "default team" in the constants section? This is the place where the term is associated to SHMEM_TEAM_WORLD.

**Review by jdinan — APPROVED** [review]

**Comment by minsii** [comment]
> Did you get the instance of "default team" in the constants section? This is the place where the term is associated to SHMEM_TEAM_WORLD.

Yes, it has been added into the front matter section.

**Pull request merged**
