### PR TITLE
Improve use of "non" vs. "non-"

### PR DESCRIPTION
**Pull request by nspark**
- [X] Remove hyphen from  non-{critical, existent, profit, standard, zero}
  - Rationale: All these are dictionary words without the hyphen.
- [X] Reword to avoid non-initializing
  - Rationale: Don't "solve" a problem you can avoid entirely.
- [ ] Fix "non-symmetric"
  - Plan: Reword use to avoid entirely

Replaces openshmem-org/specification#399
Closes openshmem-org/specification#166

### CODE REVIEW

**Comment by nspark** [comment]
We can always fix "non-symmetric" another time.

**Review by jdinan — APPROVED** [review]

**Comment by jdinan** [comment]
@nspark Would you like to review the conflict in `backmatter.tex`? Looks like the paragraph you edited was also updated to take teams into account and that update also removed the issue you fixed.

**Comment by nspark** [comment]
I think I resolved the merge by accepting the revised text.

**Review by jdinan — APPROVED** [review]
Looks good -- thanks!

**Pull request merged**
