### PR TITLE
Undefined behavior clause added for invalid ctx value

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
This looks good, but all of these changes are to sections owned by the RMA/AMO/Signals section committee. Can you please post this as a PR to their branch? That will ensure it is integrated with other edits they may be making to the same text.

**Comment by wrrobin** [comment]
Thanks @jdinan. Will do once we have a branch for that section.

**Review by agrippa — APPROVED** [review]

**Comment by wrrobin** [comment]
@shamisp Should I add this PR comparing against shamisp:topic/1.5/rma_edits?

**Review by jdinan — APPROVED** [review]

**Comment by wrrobin** [comment]
Moved to shamisp:sec/rma/1.5.0#2

**Pull request closed without merging**
