### PR TITLE
Clarify shmem_team_split_strided behavior for a zero size triplet

### PR DESCRIPTION
**Pull request by agrippa**
This is a first pass, I'm open to making changes to these clarifications.

### CODE REVIEW

**Comment by agrippa** [comment]
@nspark @jdinan @wrrobin @naveen-rn could you take a look?

**Comment by agrippa** [comment]
Addresses issue https://github.com/openshmem-org/specification/issues/320

**Comment by jdinan** [comment]
Should we also add to the `size` `apiargument` that it must be a positive integer?

**Comment by agrippa** [comment]
@jdinan I'm good with that change, just updated the PR.

**Review by jdinan — APPROVED** [review]

**Review by nspark — APPROVED** [review]

**Review by jdinan — APPROVED** [review]

**Pull request merged**
